commitizen:
  major_version_zero: true
  name: cz_customize
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.0.1
  version_scheme: pep440
  customize:
    questions:
      - type: select
        name: type
        message: "커밋 유형을 선택하세요:"
        choices:
          - value: feat
            name: "feat: 새로운 기능 추가"
          - value: fix
            name: "fix: 버그 수정"
          - value: improve
            name: "improve: 기존 기능/코드 개선"
          - value: docs
            name: "docs: 문서 작성/수정"
      - type: input
        name: subject
        message: "변경 사항을 간략히 설명하세요 (한글로):"
      - type: input
        name: body
        message: "자세한 설명을 입력하세요 (선택사항):"
      - type: input
        name: footer
        message: "관련 이슈 번호 (예: #123, 선택사항):"
    message_template: |
      {{ type }}: {{ subject }}
      {{ body }}
      {{ footer }}